on:
  workflow_call:

name: "Lint Code"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Lint files and run type-checks
        run: npm run lint
      - name: Run prettier
        run: npm run format
