on:
  push:
    branches:
      - main
      - test

name: CI/CD
jobs:
  prettier:
    uses: ./.github/workflows/lint.yml
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      branch: ${{ github.head_ref }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      domain_cert: ${{ secrets.DOMAIN_CERT }}
      db_uri: ${{ secrets.DB_URI }}
      ecr_repo_name: ${{ github.head_ref }}MeritRepo
      cluster_name: ${{ github.head_ref }}MeritCluster
      service_name: ${{ github.head_ref }}MeritService
  aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Image to ECR and Force Deployment on ECS
        uses: jaroldwong/ecr-push-and-ecs-deploy@v1.1
        with:
          ecr-registry: ${{ steps.ecr.outputs.registry }}
          ecr-repository: ${{ github.head_ref }}MeritRepo
          ecs-cluster: ${{ github.head_ref }}MeritCluster
          ecs-service: ${{ github.head_ref }}MeritService
