on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      db_uri:
        required: true
      nextauth_secret:
        required: true
      domain_cert:
        required: true
      email_server_user:
        required: true
      email_server_password:
        required: true
      terraform_state:
        required: true
      # email_from:
      #   required: true
      # email_subject:
      #   required: true
      # email_server_service:
      #   required: true
      # email_server_host:
      #   required: true
      # email_server_port:
      #   required: true

name: "Deploy Terraform"
jobs:
  instantiate:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      DOMAIN_CERT: ${{ secrets.domain_cert }}
      DB_URI: ${{ secrets.db_uri }}
      TERRAFORM_STATE: ${{ secrets.terraform_state }}

    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false
      - name: Insert Remote State File
        id: insert
        run: echo "${{ env.TERRAFORM_STATE }}" >> env/${GITHUB_REF##*/}/state.tfvars
      - name: Correct Remote State File Template
        id: correct
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}")
          sed -i "s|BRANCH_ID|$BRANCH|" env/${GITHUB_REF##*/}/state.tfvars
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: terraform init -reconfigure -backend-config="env/${GITHUB_REF##*/}/state.tfvars"
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var-file="env/${GITHUB_REF##*/}/instance.tfvars" -var branch_prefix=${GITHUB_REF##*/} -var db_uri="${{ env.DB_URI }}" -var domain_certificate="${{ env.DOMAIN_CERT }}" -var nextauth_secret="${{ secrets.nextauth_secret }}" -var email_server_user="${{ secrets.email_server_user }}" -var email_server_password="${{ secrets.email_server_password }}"
      - name: Terraform Apply
        run: terraform apply -var-file="env/${GITHUB_REF##*/}/instance.tfvars" -var branch_prefix=${GITHUB_REF##*/} -var db_uri="${{ env.DB_URI }}" -var domain_certificate="${{ env.DOMAIN_CERT }}" -var nextauth_secret="${{ secrets.nextauth_secret }}" -var email_server_user="${{ secrets.email_server_user }}" -var email_server_password="${{ secrets.email_server_password }}" -auto-approve
